// ---------------------------------------------------------------------------
// QUERY TYPING ONLY. Generated by `drizzle-kit pull` from the applied handoff DDL
// (db/schema/0000_ecofy_schema_v1.4.sql is the authoritative schema) and hand-corrected:
//   - citext columns (email/host) use the customType below
// NEVER run `drizzle-kit generate` or `drizzle-kit push` from this file.
// ---------------------------------------------------------------------------
import { pgTable, foreignKey, pgPolicy, uuid, text, inet, timestamp, unique, bigint, integer, jsonb, check, boolean, numeric, smallint, date, uniqueIndex, index, char, primaryKey, time, pgView, interval, pgSequence, pgEnum } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
import { customType } from "drizzle-orm/pg-core"

/** citext (case-insensitive text) — drizzle-kit cannot introspect it; hand-corrected after `pull`. */
export const citext = customType<{ data: string; driverData: string }>({ dataType() { return "citext"; } })

export const activityType = pgEnum("activity_type", ['CALL', 'REMARK', 'COMMENT', 'FOLLOW_UP', 'SYSTEM'])
export const apptStatus = pgEnum("appt_status", ['SCHEDULED', 'COMPLETED', 'NO_SHOW', 'CANCELLED', 'RESCHEDULED'])
export const assessMethod = pgEnum("assess_method", ['CALCULATOR', 'MANUAL', 'EPC'])
export const assetStatus = pgEnum("asset_status", ['ACTIVE', 'BUYBACK', 'REDEPLOYED', 'CLOSED'])
export const callOutcome = pgEnum("call_outcome", ['CONNECTED', 'NO_ANSWER', 'BUSY', 'SWITCHED_OFF', 'WRONG_NUMBER', 'CALL_BACK'])
export const caseSource = pgEnum("case_source", ['ECOFY_UPLOAD', 'ECOFY_MANUAL', 'CALCULATOR', 'ITARANG_SOURCED'])
export const caseStage = pgEnum("case_stage", ['S0', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'CLOSED'])
export const customerType = pgEnum("customer_type", ['INDIVIDUAL', 'BUSINESS'])
export const deviceStatus = pgEnum("device_status", ['PENDING', 'TRUSTED', 'REVOKED'])
export const eligStatus = pgEnum("elig_status", ['REQUESTED', 'ELIGIBLE', 'NOT_ELIGIBLE', 'INFO_NEEDED'])
export const emiState = pgEnum("emi_state", ['CURRENT', 'DPD_1_30', 'DPD_31_60', 'DPD_61_90', 'DPD_90_PLUS', 'CLOSED'])
export const finStatus = pgEnum("fin_status", ['SUBMITTED', 'SANCTIONED', 'REJECTED', 'CANCELLED'])
export const importStatus = pgEnum("import_status", ['UPLOADED', 'MAPPED', 'VALIDATED', 'COMMITTING', 'COMMITTED', 'FAILED'])
export const installStatus = pgEnum("install_status", ['NOT_STARTED', 'SCHEDULED', 'IN_PROGRESS', 'INSTALLED', 'COMMISSIONED', 'STOPPED'])
export const offerStatus = pgEnum("offer_status", ['DRAFT', 'SENT', 'ACCEPTED', 'SUPERSEDED', 'EXPIRED'])
export const orgKind = pgEnum("org_kind", ['ECOFY', 'ITARANG'])
export const otpPurpose = pgEnum("otp_purpose", ['ACCEPTANCE', 'REACCEPTANCE'])
export const otpStatus = pgEnum("otp_status", ['SENT', 'VERIFIED', 'EXPIRED', 'LOCKED', 'FAILED'])
export const quoteStatus = pgEnum("quote_status", ['ACTIVE', 'SUPERSEDED', 'EXPIRED', 'ACCEPTED'])
export const recoStatus = pgEnum("reco_status", ['RECOMMENDED', 'CUSTOM_REQUIRED', 'PENDING_TECHNICAL_DATA'])
export const releaseStatus = pgEnum("release_status", ['DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'REJECTED', 'RETIRED'])
export const rowResult = pgEnum("row_result", ['CREATED', 'DUPLICATE', 'REOPENED', 'REJECTED'])
export const segment = pgEnum("segment", ['RESI', 'ESS', 'CI'])
export const temperature = pgEnum("temperature", ['COLD', 'WARM', 'HOT', 'NOT_INTERESTED'])
export const userRole = pgEnum("user_role", ['ECOFY_ADMIN', 'ECOFY_USER', 'ITARANG_ADMIN', 'ITARANG_CALLER'])
export const userStatus = pgEnum("user_status", ['INVITED', 'ACTIVE', 'DEACTIVATED'])
export const withdrawStatus = pgEnum("withdraw_status", ['REQUESTED', 'CONFIRMED', 'REJECTED'])

export const caseNoSeq = pgSequence("case_no_seq", {  startWith: "1001", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const userSessions = pgTable("user_sessions", {
	userId: uuid("user_id").primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	sessionId: text("session_id").notNull(),
	device: text(),
	ip: inet(),
	startedAt: timestamp("started_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "user_sessions_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "user_sessions_user_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const importRows = pgTable("import_rows", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "import_rows_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	batchId: uuid("batch_id").notNull(),
	rowNo: integer("row_no").notNull(),
	raw: jsonb(),
	rawPurgedAt: timestamp("raw_purged_at", { withTimezone: true, mode: 'date' }),
	result: rowResult(),
	errors: jsonb(),
	caseId: uuid("case_id"),
}, (table) => [
	foreignKey({
			columns: [table.batchId],
			foreignColumns: [importBatches.id],
			name: "import_rows_batch_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "import_rows_tenant_id_fkey"
		}),
	unique("import_rows_batch_id_row_no_key").on(table.batchId, table.rowNo),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const calcAppliances = pgTable("calc_appliances", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	releaseId: uuid("release_id").notNull(),
	name: text().notNull(),
	defaultWatts: integer("default_watts").notNull(),
	isMotor: boolean("is_motor").default(false).notNull(),
	startMultiplier: numeric("start_multiplier", { precision: 4, scale:  2 }).default('1').notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	active: boolean().default(true).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.releaseId],
			foreignColumns: [calcReleases.id],
			name: "calc_appliances_release_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "calc_appliances_tenant_id_fkey"
		}),
	unique("calc_appliances_release_id_name_key").on(table.releaseId, table.name),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("calc_appliances_default_watts_check", sql`default_watts > 0`),
	check("calc_appliances_start_multiplier_check", sql`start_multiplier >= (1)::numeric`),
]);

export const calcSystems = pgTable("calc_systems", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	releaseId: uuid("release_id").notNull(),
	systemCode: text("system_code").notNull(),
	systemName: text("system_name").notNull(),
	forResi: boolean("for_resi").notNull(),
	forEss: boolean("for_ess").notNull(),
	forCi: boolean("for_ci").notNull(),
	systemType: text("system_type").notNull(),
	batteryCapacityKwh: numeric("battery_capacity_kwh", { precision: 8, scale:  2 }).notNull(),
	usableCapacityKwh: numeric("usable_capacity_kwh", { precision: 8, scale:  2 }).notNull(),
	batteryChemistry: text("battery_chemistry"),
	inverterKva: numeric("inverter_kva", { precision: 8, scale:  2 }).notNull(),
	inverterType: text("inverter_type").notNull(),
	phase: text().notNull(),
	solarKwp: numeric("solar_kwp", { precision: 8, scale:  2 }).notNull(),
	expandable: boolean(),
	maxExpansionKwh: numeric("max_expansion_kwh", { precision: 8, scale:  2 }),
	batteryWarrantyYears: smallint("battery_warranty_years"),
	inverterWarrantyYears: smallint("inverter_warranty_years"),
	equipmentPriceMinInr: integer("equipment_price_min_inr").notNull(),
	equipmentPriceMaxInr: integer("equipment_price_max_inr").notNull(),
	installationPriceMinInr: integer("installation_price_min_inr").notNull(),
	installationPriceMaxInr: integer("installation_price_max_inr").notNull(),
	gstPct: numeric("gst_pct", { precision: 5, scale:  2 }).notNull(),
	priceUpdatedOn: date("price_updated_on").notNull(),
	epcPartners: text("epc_partners"),
	active: boolean().default(true).notNull(),
	notes: text(),
}, (table) => [
	foreignKey({
			columns: [table.releaseId],
			foreignColumns: [calcReleases.id],
			name: "calc_systems_release_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "calc_systems_tenant_id_fkey"
		}),
	unique("calc_systems_release_id_system_code_key").on(table.releaseId, table.systemCode),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("calc_systems_battery_capacity_kwh_check", sql`battery_capacity_kwh >= (0)::numeric`),
	check("calc_systems_check", sql`usable_capacity_kwh <= battery_capacity_kwh`),
	check("calc_systems_check1", sql`equipment_price_max_inr >= equipment_price_min_inr`),
	check("calc_systems_check2", sql`installation_price_max_inr >= installation_price_min_inr`),
	check("calc_systems_equipment_price_min_inr_check", sql`equipment_price_min_inr > 0`),
	check("calc_systems_gst_pct_check", sql`gst_pct >= (0)::numeric`),
	check("calc_systems_installation_price_min_inr_check", sql`installation_price_min_inr >= 0`),
	check("calc_systems_inverter_kva_check", sql`inverter_kva > (0)::numeric`),
	check("calc_systems_inverter_type_check", sql`inverter_type = ANY (ARRAY['HYBRID'::text, 'OFF_GRID'::text, 'ON_GRID'::text])`),
	check("calc_systems_phase_check", sql`phase = ANY (ARRAY['SINGLE'::text, 'THREE'::text])`),
	check("calc_systems_solar_kwp_check", sql`solar_kwp >= (0)::numeric`),
	check("calc_systems_system_type_check", sql`system_type = ANY (ARRAY['SOLAR_STORAGE'::text, 'STORAGE_ONLY'::text, 'SOLAR_ONLY'::text])`),
	check("calc_systems_usable_capacity_kwh_check", sql`usable_capacity_kwh >= (0)::numeric`),
]);

export const orgs = pgTable("orgs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	kind: orgKind().notNull(),
	name: text().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "orgs_tenant_id_fkey"
		}),
	unique("orgs_tenant_id_kind_key").on(table.tenantId, table.kind),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const users = pgTable("users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	orgId: uuid("org_id").notNull(),
	authUserId: uuid("auth_user_id"),
	fullName: text("full_name").notNull(),
	email: citext("email").notNull(),
	mobileE164: text("mobile_e164"),
	role: userRole().notNull(),
	status: userStatus().default('INVITED').notNull(),
	lastLoginAt: timestamp("last_login_at", { withTimezone: true, mode: 'date' }),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	deactivatedAt: timestamp("deactivated_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	foreignKey({
			columns: [table.orgId],
			foreignColumns: [orgs.id],
			name: "users_org_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "users_tenant_id_fkey"
		}),
	unique("users_tenant_id_email_key").on(table.tenantId, table.email),
	unique("users_auth_user_id_key").on(table.authUserId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const listItems = pgTable("list_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	listCode: text("list_code").notNull(),
	code: text().notNull(),
	label: text().notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	active: boolean().default(true).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "list_items_tenant_id_fkey"
		}),
	unique("list_items_tenant_id_list_code_code_key").on(table.tenantId, table.listCode, table.code),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("list_items_check", sql`(list_code <> 'document_type'::text) OR (upper(((code || ' '::text) || label)) !~ '(^|[^A-Z])(PAN|AADHAAR|AADHAR|KYC|BANK|PASSPORT|VOTER|ITR|SALARY|CIBIL)([^A-Z]|$)'::text)`),
]);

export const epcPartners = pgTable("epc_partners", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	name: text().notNull(),
	contactName: text("contact_name"),
	mobileE164: text("mobile_e164"),
	email: citext("email"),
	pincodes: text().array().default([]).notNull(),
	segments: segment().array().default([]).notNull(),
	active: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "epc_partners_tenant_id_fkey"
		}),
	unique("epc_partners_tenant_id_name_key").on(table.tenantId, table.name),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const financiers = pgTable("financiers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	name: text().notNull(),
	isDefault: boolean("is_default").default(false).notNull(),
	valuesVisibleTo: userRole("values_visible_to").notNull(),
	active: boolean().default(true).notNull(),
}, (table) => [
	uniqueIndex("one_default_financier").using("btree", table.tenantId.asc().nullsLast().op("uuid_ops")).where(sql`is_default`),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "financiers_tenant_id_fkey"
		}),
	unique("financiers_tenant_id_name_key").on(table.tenantId, table.name),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const columnMappings = pgTable("column_mappings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	sourceName: text("source_name").notNull(),
	mapping: jsonb().notNull(),
	createdBy: uuid("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "column_mappings_created_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "column_mappings_tenant_id_fkey"
		}),
	unique("column_mappings_tenant_id_source_name_key").on(table.tenantId, table.sourceName),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const importBatches = pgTable("import_batches", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	uploadedBy: uuid("uploaded_by").notNull(),
	fileKey: text("file_key").notNull(),
	fileName: text("file_name").notNull(),
	mappingId: uuid("mapping_id"),
	status: importStatus().default('UPLOADED').notNull(),
	rowCount: integer("row_count").default(0).notNull(),
	createdCount: integer("created_count").default(0).notNull(),
	duplicateCount: integer("duplicate_count").default(0).notNull(),
	reopenedCount: integer("reopened_count").default(0).notNull(),
	rejectedCount: integer("rejected_count").default(0).notNull(),
	consentAttested: boolean("consent_attested").default(false).notNull(),
	attestationText: text("attestation_text"),
	attestedAt: timestamp("attested_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	committedAt: timestamp("committed_at", { withTimezone: true, mode: 'date' }),
	filePurgedAt: timestamp("file_purged_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	foreignKey({
			columns: [table.mappingId],
			foreignColumns: [columnMappings.id],
			name: "import_batches_mapping_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "import_batches_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.uploadedBy],
			foreignColumns: [users.id],
			name: "import_batches_uploaded_by_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("import_batches_check", sql`(status <> 'COMMITTED'::import_status) OR consent_attested`),
]);

export const caseAssignments = pgTable("case_assignments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	userId: uuid("user_id").notNull(),
	assignedBy: uuid("assigned_by").notNull(),
	reason: text(),
	assignedAt: timestamp("assigned_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	endedAt: timestamp("ended_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_open_assignment").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(ended_at IS NULL)`),
	foreignKey({
			columns: [table.assignedBy],
			foreignColumns: [users.id],
			name: "case_assignments_assigned_by_fkey"
		}),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "case_assignments_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "case_assignments_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "case_assignments_user_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const caseReturns = pgTable("case_returns", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	reasonCode: text("reason_code").notNull(),
	note: text(),
	returnedBy: uuid("returned_by").notNull(),
	returnedTo: uuid("returned_to"),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "case_returns_case_id_fkey"
		}),
	foreignKey({
			columns: [table.returnedBy],
			foreignColumns: [users.id],
			name: "case_returns_returned_by_fkey"
		}),
	foreignKey({
			columns: [table.returnedTo],
			foreignColumns: [users.id],
			name: "case_returns_returned_to_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "case_returns_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const appointments = pgTable("appointments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	meetingType: text("meeting_type").notNull(),
	scheduledAt: timestamp("scheduled_at", { withTimezone: true, mode: 'date' }).notNull(),
	status: apptStatus().default('SCHEDULED').notNull(),
	bookingRemarks: text("booking_remarks"),
	actualAt: timestamp("actual_at", { withTimezone: true, mode: 'date' }),
	meetingRemarks: text("meeting_remarks"),
	outcomeReason: text("outcome_reason"),
	epcPartnerId: uuid("epc_partner_id"),
	epcFeedback: text("epc_feedback"),
	rescheduledFrom: uuid("rescheduled_from"),
	createdBy: uuid("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("appt_case_idx").using("btree", table.caseId.asc().nullsLast().op("timestamptz_ops"), table.scheduledAt.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "appointments_case_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "appointments_created_by_fkey"
		}),
	foreignKey({
			columns: [table.epcPartnerId],
			foreignColumns: [epcPartners.id],
			name: "appointments_epc_partner_id_fkey"
		}),
	foreignKey({
			columns: [table.rescheduledFrom],
			foreignColumns: [table.id],
			name: "appointments_rescheduled_from_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "appointments_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("appointments_check", sql`(status <> 'COMPLETED'::appt_status) OR ((actual_at IS NOT NULL) AND (meeting_remarks IS NOT NULL))`),
	check("appointments_check1", sql`(status <> ALL (ARRAY['NO_SHOW'::appt_status, 'CANCELLED'::appt_status])) OR (outcome_reason IS NOT NULL)`),
	check("appointments_check2", sql`(meeting_type <> 'EPC_VISIT'::text) OR (epc_partner_id IS NOT NULL)`),
]);

export const calcReleases = pgTable("calc_releases", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	version: integer().notNull(),
	status: releaseStatus().default('DRAFT').notNull(),
	params: jsonb().notNull(),
	changeNote: text("change_note"),
	createdBy: uuid("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	submittedAt: timestamp("submitted_at", { withTimezone: true, mode: 'date' }),
	decidedBy: uuid("decided_by"),
	decidedAt: timestamp("decided_at", { withTimezone: true, mode: 'date' }),
	decisionNote: text("decision_note"),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_open_draft").using("btree", table.tenantId.asc().nullsLast().op("uuid_ops")).where(sql`(status = ANY (ARRAY['DRAFT'::release_status, 'PENDING_APPROVAL'::release_status]))`),
	uniqueIndex("one_published_release").using("btree", table.tenantId.asc().nullsLast().op("uuid_ops")).where(sql`(status = 'PUBLISHED'::release_status)`),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "calc_releases_created_by_fkey"
		}),
	foreignKey({
			columns: [table.decidedBy],
			foreignColumns: [users.id],
			name: "calc_releases_decided_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "calc_releases_tenant_id_fkey"
		}),
	unique("calc_releases_tenant_id_version_key").on(table.tenantId, table.version),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const assessments = pgTable("assessments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	version: integer().notNull(),
	method: assessMethod().notNull(),
	releaseId: uuid("release_id"),
	inputs: jsonb().notNull(),
	outputs: jsonb().notNull(),
	recommendationStatus: recoStatus("recommendation_status").notNull(),
	recommendedCode: text("recommended_code"),
	selectedCode: text("selected_code"),
	overrideReason: text("override_reason"),
	confirmedBy: uuid("confirmed_by"),
	confirmedAt: timestamp("confirmed_at", { withTimezone: true, mode: 'date' }),
	createdBy: uuid("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "assessments_case_id_fkey"
		}),
	foreignKey({
			columns: [table.confirmedBy],
			foreignColumns: [users.id],
			name: "assessments_confirmed_by_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "assessments_created_by_fkey"
		}),
	foreignKey({
			columns: [table.releaseId],
			foreignColumns: [calcReleases.id],
			name: "assessments_release_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "assessments_tenant_id_fkey"
		}),
	unique("assessments_case_id_version_key").on(table.caseId, table.version),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("assessments_check", sql`(method <> 'CALCULATOR'::assess_method) OR (release_id IS NOT NULL)`),
	check("assessments_check1", sql`(recommendation_status = 'RECOMMENDED'::reco_status) = (recommended_code IS NOT NULL)`),
	check("assessments_check2", sql`(selected_code IS NULL) OR (recommended_code IS NULL) OR (selected_code = recommended_code) OR (override_reason IS NOT NULL)`),
]);

export const eligibilityChecks = pgTable("eligibility_checks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	financierId: uuid("financier_id").notNull(),
	status: eligStatus().default('REQUESTED').notNull(),
	reason: text(),
	requestedBy: uuid("requested_by").notNull(),
	requestedAt: timestamp("requested_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	decidedBy: uuid("decided_by"),
	decidedAt: timestamp("decided_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_open_eligibility").using("btree", table.caseId.asc().nullsLast().op("uuid_ops"), table.financierId.asc().nullsLast().op("uuid_ops")).where(sql`(status = ANY (ARRAY['REQUESTED'::elig_status, 'INFO_NEEDED'::elig_status]))`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "eligibility_checks_case_id_fkey"
		}),
	foreignKey({
			columns: [table.decidedBy],
			foreignColumns: [users.id],
			name: "eligibility_checks_decided_by_fkey"
		}),
	foreignKey({
			columns: [table.financierId],
			foreignColumns: [financiers.id],
			name: "eligibility_checks_financier_id_fkey"
		}),
	foreignKey({
			columns: [table.requestedBy],
			foreignColumns: [users.id],
			name: "eligibility_checks_requested_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "eligibility_checks_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("eligibility_checks_check", sql`(status <> 'NOT_ELIGIBLE'::elig_status) OR (reason IS NOT NULL)`),
]);

export const quoteRequests = pgTable("quote_requests", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	epcPartnerId: uuid("epc_partner_id").notNull(),
	channel: text().notNull(),
	status: text().default('REQUESTED').notNull(),
	requestedBy: uuid("requested_by").notNull(),
	requestedAt: timestamp("requested_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "quote_requests_case_id_fkey"
		}),
	foreignKey({
			columns: [table.epcPartnerId],
			foreignColumns: [epcPartners.id],
			name: "quote_requests_epc_partner_id_fkey"
		}),
	foreignKey({
			columns: [table.requestedBy],
			foreignColumns: [users.id],
			name: "quote_requests_requested_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "quote_requests_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("quote_requests_channel_check", sql`channel = ANY (ARRAY['EMAIL'::text, 'WHATSAPP'::text, 'PHONE'::text])`),
	check("quote_requests_status_check", sql`status = ANY (ARRAY['REQUESTED'::text, 'RECEIVED'::text, 'DECLINED'::text])`),
]);

export const financingDecisions = pgTable("financing_decisions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	fileId: uuid("file_id").notNull(),
	financierId: uuid("financier_id").notNull(),
	attemptNo: smallint("attempt_no").notNull(),
	status: finStatus().default('SUBMITTED').notNull(),
	rejectionReason: text("rejection_reason"),
	routedBy: uuid("routed_by"),
	recordedBy: uuid("recorded_by"),
	submittedAt: timestamp("submitted_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	decidedAt: timestamp("decided_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_open_financing").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(status = 'SUBMITTED'::fin_status)`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "financing_decisions_case_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.fileId],
			foreignColumns: [files.id, files.caseId],
			name: "financing_decisions_file_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.financierId],
			foreignColumns: [financiers.id],
			name: "financing_decisions_financier_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "financing_decisions_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.routedBy],
			foreignColumns: [users.id],
			name: "financing_decisions_routed_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "financing_decisions_tenant_id_fkey"
		}),
	unique("financing_decisions_case_id_attempt_no_key").on(table.caseId, table.attemptNo),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("financing_decisions_check", sql`(status <> 'REJECTED'::fin_status) OR (rejection_reason IS NOT NULL)`),
]);

export const installations = pgTable("installations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	epcPartnerId: uuid("epc_partner_id").notNull(),
	status: installStatus().default('NOT_STARTED').notNull(),
	scheduledOn: date("scheduled_on"),
	startedOn: date("started_on"),
	completedOn: date("completed_on"),
	startedBeforeSanction: boolean("started_before_sanction").default(false).notNull(),
	stopReason: text("stop_reason"),
	updatedBy: uuid("updated_by"),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "installations_case_id_fkey"
		}),
	foreignKey({
			columns: [table.epcPartnerId],
			foreignColumns: [epcPartners.id],
			name: "installations_epc_partner_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "installations_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [users.id],
			name: "installations_updated_by_fkey"
		}),
	unique("installations_case_id_key").on(table.caseId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("installations_check", sql`(status <> 'STOPPED'::install_status) OR (stop_reason IS NOT NULL)`),
]);

export const downPayments = pgTable("down_payments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	visibleTo: userRole("visible_to").notNull(),
	receivedOn: date("received_on").notNull(),
	amountInr: integer("amount_inr").notNull(),
	reference: text(),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "down_payments_case_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "down_payments_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "down_payments_tenant_id_fkey"
		}),
	pgPolicy("dp_role", { as: "restrictive", for: "all", to: ["public"], using: sql`((visible_to)::text = app_role())`, withCheck: sql`((visible_to)::text = app_role())`  }),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"] }),
	check("down_payments_amount_inr_check", sql`amount_inr > 0`),
]);

export const disbursements = pgTable("disbursements", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	decisionId: uuid("decision_id").notNull(),
	visibleTo: userRole("visible_to").notNull(),
	disbursedOn: date("disbursed_on").notNull(),
	amountInr: integer("amount_inr").notNull(),
	reference: text(),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "disbursements_case_id_fkey"
		}),
	foreignKey({
			columns: [table.decisionId],
			foreignColumns: [financingDecisions.id],
			name: "disbursements_decision_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "disbursements_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "disbursements_tenant_id_fkey"
		}),
	unique("disbursements_case_id_key").on(table.caseId),
	pgPolicy("disb_role", { as: "restrictive", for: "all", to: ["public"], using: sql`((visible_to)::text = app_role())`, withCheck: sql`((visible_to)::text = app_role())`  }),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"] }),
	check("disbursements_amount_inr_check", sql`amount_inr > 0`),
]);

export const assets = pgTable("assets", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	systemSnapshot: jsonb("system_snapshot").notNull(),
	commissionedOn: date("commissioned_on").notNull(),
	status: assetStatus().default('ACTIVE').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "assets_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "assets_tenant_id_fkey"
		}),
	unique("assets_case_id_key").on(table.caseId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const emiStatusUpdates = pgTable("emi_status_updates", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "emi_status_updates_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	assetId: uuid("asset_id").notNull(),
	asOf: date("as_of").notNull(),
	state: emiState().notNull(),
	note: text(),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.assetId],
			foreignColumns: [assets.id],
			name: "emi_status_updates_asset_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "emi_status_updates_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "emi_status_updates_tenant_id_fkey"
		}),
	unique("emi_status_updates_asset_id_as_of_key").on(table.assetId, table.asOf),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const assetEvents = pgTable("asset_events", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "asset_events_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	assetId: uuid("asset_id").notNull(),
	type: text().notNull(),
	onDate: date("on_date").notNull(),
	note: text(),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.assetId],
			foreignColumns: [assets.id],
			name: "asset_events_asset_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "asset_events_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "asset_events_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("asset_events_type_check", sql`type = ANY (ARRAY['BUYBACK'::text, 'REDEPLOYED'::text, 'CLOSED'::text])`),
]);

export const withdrawals = pgTable("withdrawals", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	stageAtRequest: caseStage("stage_at_request").notNull(),
	reason: text().notNull(),
	status: withdrawStatus().default('REQUESTED').notNull(),
	requestedBy: uuid("requested_by").notNull(),
	requestedAt: timestamp("requested_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	confirmedBy: uuid("confirmed_by"),
	confirmedAt: timestamp("confirmed_at", { withTimezone: true, mode: 'date' }),
	ecofyAlertedAt: timestamp("ecofy_alerted_at", { withTimezone: true, mode: 'date' }),
	sanctionCancelledAt: timestamp("sanction_cancelled_at", { withTimezone: true, mode: 'date' }),
	epcInformedAt: timestamp("epc_informed_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_open_withdrawal").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(status = 'REQUESTED'::withdraw_status)`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "withdrawals_case_id_fkey"
		}),
	foreignKey({
			columns: [table.confirmedBy],
			foreignColumns: [users.id],
			name: "withdrawals_confirmed_by_fkey"
		}),
	foreignKey({
			columns: [table.requestedBy],
			foreignColumns: [users.id],
			name: "withdrawals_requested_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "withdrawals_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const documents = pgTable("documents", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id"),
	typeCode: text("type_code").notNull(),
	s3Key: text("s3_key").notNull(),
	fileName: text("file_name").notNull(),
	mimeType: text("mime_type").notNull(),
	sizeBytes: integer("size_bytes").notNull(),
	sha256: char({ length: 64 }).notNull(),
	recordingConsent: boolean("recording_consent"),
	retentionUntil: date("retention_until"),
	uploadedBy: uuid("uploaded_by").notNull(),
	uploadedAt: timestamp("uploaded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("docs_case_idx").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(deleted_at IS NULL)`),
	index("docs_retention_idx").using("btree", table.retentionUntil.asc().nullsLast().op("date_ops")).where(sql`((deleted_at IS NULL) AND (retention_until IS NOT NULL))`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "documents_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "documents_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.uploadedBy],
			foreignColumns: [users.id],
			name: "documents_uploaded_by_fkey"
		}),
	unique("documents_id_case_id_key").on(table.id, table.caseId),
	unique("documents_s3_key_key").on(table.s3Key),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("documents_check", sql`(type_code <> 'CALL_RECORDING'::text) OR (recording_consent AND (retention_until IS NOT NULL))`),
	check("documents_size_bytes_check", sql`(size_bytes > 0) AND (size_bytes <= 26214400)`),
]);

export const notifications = pgTable("notifications", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "notifications_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	userId: uuid("user_id").notNull(),
	type: text().notNull(),
	title: text().notNull(),
	body: text(),
	caseId: uuid("case_id"),
	readAt: timestamp("read_at", { withTimezone: true, mode: 'date' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("notif_user_idx").using("btree", table.userId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")).where(sql`(read_at IS NULL)`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "notifications_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "notifications_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "notifications_user_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const smsMessages = pgTable("sms_messages", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "sms_messages_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id"),
	dltTemplateId: text("dlt_template_id").notNull(),
	toMobileE164: text("to_mobile_e164").notNull(),
	purpose: text().notNull(),
	provider: text().default('GUPSHUP').notNull(),
	providerMsgId: text("provider_msg_id"),
	status: text().default('QUEUED').notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }),
	deliveredAt: timestamp("delivered_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "sms_messages_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "sms_messages_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("sms_messages_status_check", sql`status = ANY (ARRAY['QUEUED'::text, 'SENT'::text, 'DELIVERED'::text, 'FAILED'::text])`),
]);

export const outboxEvents = pgTable("outbox_events", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "outbox_events_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	eventType: text("event_type").notNull(),
	aggregateId: uuid("aggregate_id").notNull(),
	payload: jsonb().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	index("outbox_unpublished").using("btree", table.id.asc().nullsLast().op("int8_ops")).where(sql`(published_at IS NULL)`),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "outbox_events_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const funnelDaily = pgTable("funnel_daily", {
	tenantId: uuid("tenant_id").notNull(),
	day: date().notNull(),
	userId: uuid("user_id"),
	stage: caseStage().notNull(),
	entered: integer().default(0).notNull(),
	exited: integer().default(0).notNull(),
	openAtEod: integer("open_at_eod").default(0).notNull(),
}, (table) => [
	uniqueIndex("funnel_daily_key").using("btree", sql`tenant_id`, sql`day`, sql`stage`, sql`COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid)`),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "funnel_daily_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const eligibilityValues = pgTable("eligibility_values", {
	eligibilityId: uuid("eligibility_id").primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	visibleTo: userRole("visible_to").notNull(),
	maxEligibleInr: integer("max_eligible_inr").notNull(),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.eligibilityId],
			foreignColumns: [eligibilityChecks.id],
			name: "eligibility_values_eligibility_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "eligibility_values_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "eligibility_values_tenant_id_fkey"
		}),
	pgPolicy("values_role", { as: "permissive", for: "all", to: ["public"], using: sql`((tenant_id = app_tenant()) AND ((visible_to)::text = app_role()))`, withCheck: sql`((tenant_id = app_tenant()) AND ((visible_to)::text = app_role()))`  }),
	check("eligibility_values_max_eligible_inr_check", sql`max_eligible_inr > 0`),
]);

export const financingValues = pgTable("financing_values", {
	decisionId: uuid("decision_id").primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	visibleTo: userRole("visible_to").notNull(),
	sanctionedInr: integer("sanctioned_inr"),
	downPaymentInr: integer("down_payment_inr"),
	tenureMonths: smallint("tenure_months"),
	emiInr: integer("emi_inr"),
	lenderFileNo: text("lender_file_no"),
	recordedBy: uuid("recorded_by").notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.decisionId],
			foreignColumns: [financingDecisions.id],
			name: "financing_values_decision_id_fkey"
		}),
	foreignKey({
			columns: [table.recordedBy],
			foreignColumns: [users.id],
			name: "financing_values_recorded_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "financing_values_tenant_id_fkey"
		}),
	pgPolicy("values_role", { as: "permissive", for: "all", to: ["public"], using: sql`((tenant_id = app_tenant()) AND ((visible_to)::text = app_role()))`, withCheck: sql`((tenant_id = app_tenant()) AND ((visible_to)::text = app_role()))`  }),
	check("financing_values_down_payment_inr_check", sql`down_payment_inr >= 0`),
	check("financing_values_sanctioned_inr_check", sql`sanctioned_inr > 0`),
]);

export const tenants = pgTable("tenants", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	code: text().notNull(),
	name: text().notNull(),
	status: text().default('ACTIVE').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	unique("tenants_code_key").on(table.code),
	pgPolicy("tenant_self", { as: "permissive", for: "all", to: ["public"], using: sql`(id = app_tenant())` }),
	check("tenants_status_check", sql`status = ANY (ARRAY['ACTIVE'::text, 'READ_ONLY'::text, 'EXITED'::text])`),
]);

export const tenantDomains = pgTable("tenant_domains", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	host: citext("host").notNull(),
	isPrimary: boolean("is_primary").default(true).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "tenant_domains_tenant_id_fkey"
		}),
	unique("tenant_domains_host_key").on(table.host),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const auditLog = pgTable("audit_log", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "audit_log_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	actorId: uuid("actor_id"),
	actorRole: userRole("actor_role"),
	action: text().notNull(),
	entityType: text("entity_type").notNull(),
	entityId: text("entity_id").notNull(),
	caseId: uuid("case_id"),
	before: jsonb(),
	after: jsonb(),
	reason: text(),
	ip: inet(),
	userAgent: text("user_agent"),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("audit_actor_idx").using("btree", table.tenantId.asc().nullsLast().op("timestamptz_ops"), table.actorId.asc().nullsLast().op("uuid_ops"), table.at.asc().nullsLast().op("uuid_ops")),
	index("audit_case_idx").using("btree", table.caseId.asc().nullsLast().op("uuid_ops"), table.at.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.actorId],
			foreignColumns: [users.id],
			name: "audit_log_actor_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "audit_log_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const activities = pgTable("activities", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "activities_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	type: activityType().notNull(),
	callOutcome: callOutcome("call_outcome"),
	note: text(),
	nextFollowUpAt: timestamp("next_follow_up_at", { withTimezone: true, mode: 'date' }),
	actorId: uuid("actor_id"),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("act_case_idx").using("btree", table.caseId.asc().nullsLast().op("timestamptz_ops"), table.at.asc().nullsLast().op("timestamptz_ops")),
	index("act_followup_idx").using("btree", table.tenantId.asc().nullsLast().op("uuid_ops"), table.nextFollowUpAt.asc().nullsLast().op("uuid_ops")).where(sql`(next_follow_up_at IS NOT NULL)`),
	foreignKey({
			columns: [table.actorId],
			foreignColumns: [users.id],
			name: "activities_actor_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "activities_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "activities_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("activities_check", sql`(type <> 'CALL'::activity_type) OR (call_outcome IS NOT NULL)`),
]);

export const caseStageHistory = pgTable("case_stage_history", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "case_stage_history_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	fromStage: caseStage("from_stage"),
	toStage: caseStage("to_stage").notNull(),
	subStatus: text("sub_status"),
	reason: text(),
	actorId: uuid("actor_id"),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("csh_case_idx").using("btree", table.caseId.asc().nullsLast().op("timestamptz_ops"), table.at.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.actorId],
			foreignColumns: [users.id],
			name: "case_stage_history_actor_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "case_stage_history_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "case_stage_history_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const seatLedger = pgTable("seat_ledger", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "seat_ledger_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	role: userRole().notNull(),
	action: text().notNull(),
	userId: uuid("user_id"),
	oldLimit: integer("old_limit"),
	newLimit: integer("new_limit"),
	actorId: uuid("actor_id").notNull(),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.actorId],
			foreignColumns: [users.id],
			name: "seat_ledger_actor_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "seat_ledger_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "seat_ledger_user_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("seat_ledger_action_check", sql`action = ANY (ARRAY['SEAT_ADDED'::text, 'SEAT_RELEASED'::text, 'LIMIT_CHANGED'::text])`),
]);

export const installationEvents = pgTable("installation_events", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "installation_events_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	installationId: uuid("installation_id").notNull(),
	status: installStatus().notNull(),
	note: text(),
	actorId: uuid("actor_id").notNull(),
	at: timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.actorId],
			foreignColumns: [users.id],
			name: "installation_events_actor_id_fkey"
		}),
	foreignKey({
			columns: [table.installationId],
			foreignColumns: [installations.id],
			name: "installation_events_installation_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "installation_events_tenant_id_fkey"
		}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const fileAcceptances = pgTable("file_acceptances", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	fileId: uuid("file_id").notNull(),
	kind: text().notNull(),
	offerId: uuid("offer_id").notNull(),
	otpChallengeId: uuid("otp_challenge_id").notNull(),
	acceptedAt: timestamp("accepted_at", { withTimezone: true, mode: 'date' }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId, table.fileId],
			foreignColumns: [files.id, files.caseId],
			name: "file_acceptances_file_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.offerId],
			foreignColumns: [offers.id, offers.caseId],
			name: "file_acceptances_offer_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.otpChallengeId],
			foreignColumns: [otpChallenges.id, otpChallenges.caseId],
			name: "file_acceptances_otp_challenge_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "file_acceptances_tenant_id_fkey"
		}),
	unique("file_acceptances_otp_challenge_id_key").on(table.otpChallengeId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("file_acceptances_kind_check", sql`kind = ANY (ARRAY['INITIAL'::text, 'REVISED'::text])`),
]);

export const cases = pgTable("cases", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseNo: text("case_no").default(sql`(\'ECF-\'::text || nextval(\'case_no_seq\'::regclass))`).notNull(),
	customerId: uuid("customer_id").notNull(),
	segment: segment().notNull(),
	source: caseSource().notNull(),
	ownerOrgId: uuid("owner_org_id").notNull(),
	stage: caseStage().default('S0').notNull(),
	subStatus: text("sub_status"),
	stageEnteredAt: timestamp("stage_entered_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	temperature: temperature(),
	qualifiedBy: uuid("qualified_by"),
	assignedUserId: uuid("assigned_user_id"),
	queueEnteredAt: timestamp("queue_entered_at", { withTimezone: true, mode: 'date' }),
	firstCallAt: timestamp("first_call_at", { withTimezone: true, mode: 'date' }),
	financierId: uuid("financier_id"),
	productInterest: text("product_interest"),
	avgMonthlyBillInr: integer("avg_monthly_bill_inr"),
	sanctionedLoadKw: numeric("sanctioned_load_kw", { precision: 8, scale:  2 }),
	existingBackup: text("existing_backup"),
	preferredCallTime: text("preferred_call_time"),
	ecofyLeadId: text("ecofy_lead_id"),
	importBatchId: uuid("import_batch_id"),
	closureReason: text("closure_reason"),
	closureNote: text("closure_note"),
	closedAt: timestamp("closed_at", { withTimezone: true, mode: 'date' }),
	reopenCount: integer("reopen_count").default(0).notNull(),
	previousCaseId: uuid("previous_case_id"),
	version: integer().default(1).notNull(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	index("cases_assignee_idx").using("btree", table.tenantId.asc().nullsLast().op("uuid_ops"), table.assignedUserId.asc().nullsLast().op("uuid_ops")).where(sql`(stage <> 'CLOSED'::case_stage)`),
	index("cases_stage_idx").using("btree", table.tenantId.asc().nullsLast().op("enum_ops"), table.stage.asc().nullsLast().op("timestamptz_ops"), table.stageEnteredAt.asc().nullsLast().op("timestamptz_ops")),
	uniqueIndex("one_open_case_per_customer").using("btree", table.customerId.asc().nullsLast().op("uuid_ops")).where(sql`(stage <> 'CLOSED'::case_stage)`),
	foreignKey({
			columns: [table.assignedUserId],
			foreignColumns: [users.id],
			name: "cases_assigned_user_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "cases_created_by_fkey"
		}),
	foreignKey({
			columns: [table.customerId],
			foreignColumns: [customers.id],
			name: "cases_customer_id_fkey"
		}),
	foreignKey({
			columns: [table.financierId],
			foreignColumns: [financiers.id],
			name: "cases_financier_id_fkey"
		}),
	foreignKey({
			columns: [table.importBatchId],
			foreignColumns: [importBatches.id],
			name: "cases_import_batch_id_fkey"
		}),
	foreignKey({
			columns: [table.ownerOrgId],
			foreignColumns: [orgs.id],
			name: "cases_owner_org_id_fkey"
		}),
	foreignKey({
			columns: [table.previousCaseId],
			foreignColumns: [table.id],
			name: "cases_previous_case_id_fkey"
		}),
	foreignKey({
			columns: [table.qualifiedBy],
			foreignColumns: [users.id],
			name: "cases_qualified_by_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "cases_tenant_id_fkey"
		}),
	unique("cases_case_no_key").on(table.caseNo),
	pgPolicy("case_scope", { as: "restrictive", for: "all", to: ["public"], using: sql`((app_role() = 'ITARANG_ADMIN'::text) OR ((app_role() = 'ECOFY_ADMIN'::text) AND ((owner_org_id IN ( SELECT o.id
   FROM orgs o
  WHERE (o.kind = 'ECOFY'::org_kind))) OR (financier_id IN ( SELECT f.id
   FROM financiers f
  WHERE f.is_default)))) OR ((app_role() = ANY (ARRAY['ECOFY_USER'::text, 'ITARANG_CALLER'::text])) AND ((assigned_user_id = app_user()) OR (qualified_by = app_user()))))` }),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"] }),
	check("cases_avg_monthly_bill_inr_check", sql`avg_monthly_bill_inr >= 0`),
	check("cases_check", sql`(stage <> 'CLOSED'::case_stage) OR (closure_reason IS NOT NULL)`),
]);

export const customers = pgTable("customers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	fullName: text("full_name").notNull(),
	mobileE164: text("mobile_e164").notNull(),
	altMobileE164: text("alt_mobile_e164"),
	email: citext("email"),
	customerType: customerType("customer_type").notNull(),
	businessName: text("business_name"),
	address: text().notNull(),
	city: text().notNull(),
	state: text().notNull(),
	pincode: char({ length: 6 }).notNull(),
	preferredLanguage: text("preferred_language"),
	propertyType: text("property_type"),
	consentObtained: boolean("consent_obtained").notNull(),
	consentDate: date("consent_date").notNull(),
	consentSource: text("consent_source").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "customers_tenant_id_fkey"
		}),
	unique("customers_tenant_id_mobile_e164_key").on(table.tenantId, table.mobileE164),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("customers_check", sql`(customer_type = 'INDIVIDUAL'::customer_type) OR (business_name IS NOT NULL)`),
	check("customers_consent_obtained_check", sql`CHECK (consent_obtained)`),
	check("customers_mobile_e164_check", sql`mobile_e164 ~ '^\+91[6-9][0-9]{9}$'::text`),
	check("customers_pincode_check", sql`pincode ~ '^[1-9][0-9]{5}$'::text`),
]);

export const files = pgTable("files", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	fileNo: text("file_no").notNull(),
	caseId: uuid("case_id").notNull(),
	acceptedQuoteId: uuid("accepted_quote_id").notNull(),
	quoteVersion: integer("quote_version").notNull(),
	acceptedTotalInr: integer("accepted_total_inr").notNull(),
	method: text().default('SMS_OTP').notNull(),
	otpChallengeId: uuid("otp_challenge_id").notNull(),
	acceptedAt: timestamp("accepted_at", { withTimezone: true, mode: 'date' }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.caseId, table.acceptedQuoteId, table.quoteVersion],
			foreignColumns: [quotes.id, quotes.caseId, quotes.version],
			name: "files_accepted_quote_id_case_id_quote_version_fkey"
		}),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "files_case_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.otpChallengeId],
			foreignColumns: [otpChallenges.id, otpChallenges.caseId],
			name: "files_otp_challenge_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "files_tenant_id_fkey"
		}),
	unique("files_id_case_id_key").on(table.id, table.caseId),
	unique("files_file_no_key").on(table.fileNo),
	unique("files_case_id_key").on(table.caseId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const quotes = pgTable("quotes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	version: integer().notNull(),
	epcPartnerId: uuid("epc_partner_id").notNull(),
	quoteRequestId: uuid("quote_request_id"),
	assessmentId: uuid("assessment_id").notNull(),
	provisional: boolean().default(false).notNull(),
	provisionalReason: text("provisional_reason"),
	documentId: uuid("document_id").notNull(),
	systemDesc: text("system_desc").notNull(),
	batteryKwh: numeric("battery_kwh", { precision: 8, scale:  2 }),
	inverterKva: numeric("inverter_kva", { precision: 8, scale:  2 }),
	solarKwp: numeric("solar_kwp", { precision: 8, scale:  2 }),
	equipmentInr: integer("equipment_inr").notNull(),
	installationInr: integer("installation_inr").notNull(),
	gstInr: integer("gst_inr").notNull(),
	totalInr: integer("total_inr").generatedAlwaysAs(sql`((equipment_inr + installation_inr) + gst_inr)`),
	validUntil: date("valid_until").notNull(),
	notes: text(),
	status: quoteStatus().default('ACTIVE').notNull(),
	uploadedBy: uuid("uploaded_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("one_active_quote").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(status = 'ACTIVE'::quote_status)`),
	foreignKey({
			columns: [table.assessmentId],
			foreignColumns: [assessments.id],
			name: "quotes_assessment_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "quotes_case_id_fkey"
		}),
	foreignKey({
			columns: [table.documentId],
			foreignColumns: [documents.id],
			name: "quotes_document_fk"
		}),
	foreignKey({
			columns: [table.caseId, table.documentId],
			foreignColumns: [documents.id, documents.caseId],
			name: "quotes_document_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.epcPartnerId],
			foreignColumns: [epcPartners.id],
			name: "quotes_epc_partner_id_fkey"
		}),
	foreignKey({
			columns: [table.quoteRequestId],
			foreignColumns: [quoteRequests.id],
			name: "quotes_quote_request_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "quotes_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.uploadedBy],
			foreignColumns: [users.id],
			name: "quotes_uploaded_by_fkey"
		}),
	unique("quotes_id_case_id_key").on(table.id, table.caseId),
	unique("quotes_id_case_id_version_key").on(table.id, table.caseId, table.version),
	unique("quotes_case_id_version_key").on(table.caseId, table.version),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("quotes_check", sql`(NOT provisional) OR (provisional_reason IS NOT NULL)`),
	check("quotes_equipment_inr_check", sql`equipment_inr >= 0`),
	check("quotes_gst_inr_check", sql`gst_inr >= 0`),
	check("quotes_installation_inr_check", sql`installation_inr >= 0`),
]);

export const offers = pgTable("offers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	quoteId: uuid("quote_id").notNull(),
	version: integer().notNull(),
	withinLimit: boolean("within_limit"),
	content: jsonb().notNull(),
	status: offerStatus().default('DRAFT').notNull(),
	createdBy: uuid("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	uniqueIndex("one_live_offer").using("btree", table.caseId.asc().nullsLast().op("uuid_ops")).where(sql`(status = ANY (ARRAY['DRAFT'::offer_status, 'SENT'::offer_status]))`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "offers_case_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "offers_created_by_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.quoteId],
			foreignColumns: [quotes.id, quotes.caseId],
			name: "offers_quote_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "offers_tenant_id_fkey"
		}),
	unique("offers_id_case_id_key").on(table.id, table.caseId),
	unique("offers_case_id_version_key").on(table.caseId, table.version),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const otpChallenges = pgTable("otp_challenges", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull(),
	caseId: uuid("case_id").notNull(),
	offerId: uuid("offer_id").notNull(),
	purpose: otpPurpose().notNull(),
	mobileE164: text("mobile_e164").notNull(),
	codeHash: text("code_hash").notNull(),
	status: otpStatus().default('SENT').notNull(),
	attempts: smallint().default(0).notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }).notNull(),
	verifiedAt: timestamp("verified_at", { withTimezone: true, mode: 'date' }),
	providerMsgId: text("provider_msg_id"),
	triggeredBy: uuid("triggered_by").notNull(),
	idempotencyKey: text("idempotency_key").notNull(),
}, (table) => [
	uniqueIndex("one_live_otp").using("btree", table.offerId.asc().nullsLast().op("uuid_ops")).where(sql`(status = 'SENT'::otp_status)`),
	foreignKey({
			columns: [table.caseId],
			foreignColumns: [cases.id],
			name: "otp_challenges_case_id_fkey"
		}),
	foreignKey({
			columns: [table.caseId, table.offerId],
			foreignColumns: [offers.id, offers.caseId],
			name: "otp_challenges_offer_id_case_id_fkey"
		}),
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "otp_challenges_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.triggeredBy],
			foreignColumns: [users.id],
			name: "otp_challenges_triggered_by_fkey"
		}),
	unique("otp_challenges_id_case_id_key").on(table.id, table.caseId),
	unique("otp_challenges_tenant_id_idempotency_key_key").on(table.tenantId, table.idempotencyKey),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("otp_challenges_attempts_check", sql`attempts <= 5`),
]);

export const holidays = pgTable("holidays", {
	tenantId: uuid("tenant_id").notNull(),
	day: date().notNull(),
	name: text().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "holidays_tenant_id_fkey"
		}),
	primaryKey({ columns: [table.tenantId, table.day], name: "holidays_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const seatLimits = pgTable("seat_limits", {
	tenantId: uuid("tenant_id").notNull(),
	role: userRole().notNull(),
	seatLimit: integer("seat_limit").notNull(),
	seatsUsed: integer("seats_used").default(0).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "seat_limits_tenant_id_fkey"
		}),
	primaryKey({ columns: [table.tenantId, table.role], name: "seat_limits_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("seat_limits_check", sql`(seats_used >= 0) AND (seats_used <= seat_limit)`),
	check("seat_limits_seat_limit_check", sql`seat_limit >= 0`),
]);

export const workingHours = pgTable("working_hours", {
	tenantId: uuid("tenant_id").notNull(),
	weekday: smallint().notNull(),
	startTime: time("start_time").notNull(),
	endTime: time("end_time").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "working_hours_tenant_id_fkey"
		}),
	primaryKey({ columns: [table.tenantId, table.weekday], name: "working_hours_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("working_hours_check", sql`end_time > start_time`),
	check("working_hours_weekday_check", sql`(weekday >= 1) AND (weekday <= 7)`),
]);

export const settings = pgTable("settings", {
	tenantId: uuid("tenant_id").notNull(),
	key: text().notNull(),
	value: jsonb().notNull(),
	updatedBy: uuid("updated_by"),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "settings_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [users.id],
			name: "settings_updated_by_fkey"
		}),
	primaryKey({ columns: [table.tenantId, table.key], name: "settings_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const idempotencyKeys = pgTable("idempotency_keys", {
	tenantId: uuid("tenant_id").notNull(),
	key: text().notNull(),
	userId: uuid("user_id").notNull(),
	route: text().notNull(),
	requestHash: char("request_hash", { length: 64 }).notNull(),
	statusCode: smallint("status_code"),
	response: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "idempotency_keys_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "idempotency_keys_user_id_fkey"
		}),
	primaryKey({ columns: [table.tenantId, table.key], name: "idempotency_keys_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const trustedDevices = pgTable("trusted_devices", {
	tenantId: uuid("tenant_id").notNull(),
	userId: uuid("user_id").notNull(),
	deviceHash: char("device_hash", { length: 64 }).notNull(),
	status: deviceStatus().default('PENDING').notNull(),
	codeHash: text("code_hash"),
	codeExpiresAt: timestamp("code_expires_at", { withTimezone: true, mode: 'date' }),
	attempts: smallint().default(0).notNull(),
	lockedUntil: timestamp("locked_until", { withTimezone: true, mode: 'date' }),
	trustedUntil: timestamp("trusted_until", { withTimezone: true, mode: 'date' }),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	foreignKey({
			columns: [table.tenantId],
			foreignColumns: [tenants.id],
			name: "trusted_devices_tenant_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "trusted_devices_user_id_fkey"
		}),
	primaryKey({ columns: [table.userId, table.deviceHash], name: "trusted_devices_pkey"}),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
	check("trusted_devices_attempts_check", sql`attempts <= 5`),
	check("trusted_devices_check", sql`(status <> 'TRUSTED'::device_status) OR (trusted_until IS NOT NULL)`),
]);
export const vCaseAgeing = pgView("v_case_ageing", {	tenantId: uuid("tenant_id"),
	caseId: uuid("case_id"),
	caseNo: text("case_no"),
	stage: caseStage(),
	assignedUserId: uuid("assigned_user_id"),
	ownerOrgId: uuid("owner_org_id"),
	inStageFor: interval("in_stage_for"),
	openFor: interval("open_for"),
	hotToFirstCall: interval("hot_to_first_call"),
}).with({"securityInvoker":true}).as(sql`SELECT tenant_id, id AS case_id, case_no, stage, assigned_user_id, owner_org_id, now() - stage_entered_at AS in_stage_for, now() - created_at AS open_for, first_call_at - queue_entered_at AS hot_to_first_call FROM cases c WHERE stage <> 'CLOSED'::case_stage`);
// ---------------------------------------------------------------------------
// db/schema/0001_itarang_crm_sync.sql — written by hand to match the DDL (same rules: typing only).
// ---------------------------------------------------------------------------
export const integrationLinks = pgTable("integration_links", {
	tenantId: uuid("tenant_id").notNull(),
	system: text().notNull(),
	caseId: uuid("case_id").notNull(),
	externalId: text("external_id").notNull(),
	linkedAt: timestamp("linked_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	primaryKey({ columns: [table.tenantId, table.system, table.caseId], name: "integration_links_pkey" }),
	unique("integration_links_tenant_id_system_external_id_key").on(table.tenantId, table.system, table.externalId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const integrationDeliveries = pgTable("integration_deliveries", {
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "integration_deliveries_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	tenantId: uuid("tenant_id").notNull(),
	system: text().notNull(),
	outboxEventId: bigint("outbox_event_id", { mode: "number" }).notNull(),
	eventType: text("event_type").notNull(),
	caseId: uuid("case_id"),
	body: jsonb().notNull(),
	status: text().default('PENDING').notNull(),
	attempts: integer().default(0).notNull(),
	nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	lastStatus: smallint("last_status"),
	lastError: text("last_error"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
	unique("integration_deliveries_tenant_id_system_outbox_event_id_key").on(table.tenantId, table.system, table.outboxEventId),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);

export const integrationInbox = pgTable("integration_inbox", {
	tenantId: uuid("tenant_id").notNull(),
	system: text().notNull(),
	eventId: text("event_id").notNull(),
	eventType: text("event_type").notNull(),
	caseId: uuid("case_id"),
	status: text().notNull(),
	httpStatus: smallint("http_status").notNull(),
	result: jsonb().notNull(),
	receivedAt: timestamp("received_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
	primaryKey({ columns: [table.tenantId, table.system, table.eventId], name: "integration_inbox_pkey" }),
	pgPolicy("tenant_isolation", { as: "permissive", for: "all", to: ["public"], using: sql`(tenant_id = app_tenant())`, withCheck: sql`(tenant_id = app_tenant())`  }),
]);
